services:
    nginx:
        image: "nginx:stable-alpine"
        ports:
            - "8000:80"
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
            - ./:/var/www/laravel
        depends_on:
            - mysql
            - php
    php:
        build:
            context: dockerfiles
            dockerfile: php.Dockerfile
        volumes:
            - ./:/var/www/laravel
    mysql:
        image: mysql:8.0
        ports:
            - "3316:3306"
        env_file:
            - env/mysql.env
    mailpit:
        image: axllent/mailpit
        ports:
            - '${FORWARD_MAILPIT_PORT:-8025}:8025'
            - '1025:1025'

    node:
        image: node:22-alpine
        working_dir: /var/www/laravel
        volumes:
            - ./:/var/www/laravel
        ports:
            - "5173:5173"
        command: tail -f /dev/null


